language: ruby
script: "bundle exec rake test SPEC_OPTS='--format documentation'"

matrix:
  fast_finish: true
  include:
      env: PUPPET_GEM_VERSION="~> 4.9.0"
    - rvm: 2.1.9
      env: PUPPET_GEM_VERSION="~> 4.10.0"
    - rvm: 2.4.0
      env: PUPPET_GEM_VERSION="~> 5.0.0"
    - rvm: 2.4.0
      env: PUPPET_GEM_VERSION="~> 5.1.0"
