language: ruby
script: "bundle exec rake test SPEC_OPTS='--format documentation'"
rvm:
  - 1.9.3
  - 2.0
  - 2.1
  - 2.2


env:
  - PUPPET_VERSION="~> 3.6.2"
  - PUPPET_VERSION="~> 3.7.0"
  - PUPPET_VERSION="~> 3.8.0"
  - PUPPET_VERSION="~> 4.0.0"
  - PUPPET_VERSION="~> 4.1.0"
  - PUPPET_VERSION="~> 4.2.0"
  - PUPPET_VERSION="~> 4.3.0"
  - PUPPET_VERSION="~> 4.4.0"
  - PUPPET_VERSION="~> 4.5.0"


matrix:
  exclude:
    - rvm: 2.2
      env: PUPPET_VERSION="~> 3.6.2"
    - rvm: 2.2
      env: PUPPET_VERSION="~> 3.7.0"
    - rvm: 2.2
      env: PUPPET_VERSION="~> 3.8.0"
